### ISSUE TITLE
PhantomJS was not recognised

### ISSUE THREAD

**Issue by rigens** [omrilotan/isbot#208]
User Agent String
-------
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 Safari/538.1

Reproduce
-------
Node version v14.21.3

```js
let ua = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 Safari/538.1';
console.log(isbot(ua)) //3.6.1 - true, 3.6.6 - false
```

Is this library really production ready?

**Comment by omrilotan** [comment]
Sure, we can support this substring. Just remember that PhantomJS supports any user agent string (the default string is "phantomjs"). So we'll support those who include PhantomJS in the user agent string.

**Comment by omrilotan** [comment]
Would you care to review it? #209

**Comment by omrilotan** [comment]
Since the default user agent string of PhantomJS is "phantomjs" it is more efficient to check it from the start.

This repository works with [4 different databases](https://github.com/omrilotan/isbot#crawlers-user-agents) to remain updated and has rules to keep efficiency optimal. This is done so we catch all the *popular* bot user agent strings, but do not sacrifice timing.

I'd be happy to know where you encountered this user agent string.

**Comment by romis2012** [comment]
We have the same problem. Please publish new release. 

> ...it is more efficient to check it from the start

First of all, you need to ensure correctness and backward compatibility, and only then take care of performance

**Comment by omrilotan** [comment]
Correctness is ensured across a total of 5 databases
