### ISSUE TITLE
Instagram browser (Moto G) was wrongly recognised as a bot

### ISSUE THREAD

**Issue by fluteboi** [omrilotan/isbot#257]
The below user agent is wrongly flagged as a bot.

User Agent String
-------
Mozilla/5.0 (Linux; Android 12; moto g(50) 5G Build/S1RSS32.38-20-9-13; wv) AppleWebKit/537.36 (KHTML,like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36 Instagram 333.0.0.42.91 Android (31/12; 280dpi; 720x1462; motorola; moto g(50) 5G; saipan; mt6833; pt_BR; 604247853)

**Comment by omrilotan** [comment]
Thank you for the ticket. I will look into it and offer an ammendment

**Comment by omrilotan** [comment]
Feel free to review #258

**Comment by fluteboi** [comment]
Thanks for the quick fix

**Comment by sagrawal31** [comment]
This UA also considered as bot `Mozilla/5.0 (Linux; Android 13; 23028RN4DI Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36 Instagram 308.0.0.36.109 Android (33/13; 320dpi; 720x1460; Xiaomi/Redmi; 23028RN4DI; cloud; mt6765; en_IN; 534961943)` because of the `cloud` word.

But it seems that this is a real device/visitor. Should I open a new one?
