### ISSUE TITLE
Bytespider was not recognized

### ISSUE THREAD

**Issue by Woorooo** [omrilotan/isbot#268]
User Agent String
-------
Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; spider-feedback@bytedance.com)

Reproduce
-------
When integrated via https://www.jsdelivr.com/package/npm/isbot CDN, through both UMD and ESM.
The real Bytespider is never recognized. 
However when faking the user string via Chrome extension, it does recognize it.

**Comment by omrilotan** [comment]
If you're using ibot on the browser, it makes sense. Because browser using older versions of Javascript use a more simplistic pattern.
See https://github.com/omrilotan/isbot?tab=readme-ov-file#fallback
However, I will be inclined to add the substring "spider" to the simple pattern and check how it affects its efficiency.
I will try to look into it tonight

**Comment by Woorooo** [comment]
It looks like substring "spider" is already in the simple pattern
detection. Can the issue be caused by something else?

**Comment by omrilotan** [comment]
Maybe it doesn't support the Navigator interface. Would you like to share steps to reproduce?

**Comment by Woorooo** [comment]
Sorry, I guess I made a mistake. It seems that isbot script is not being loaded by Bytespider at all, so there is no response. I forgot that I was logging only detected bots, so those that block js files will not be identified.
